-- Official OFAC source snapshots. This migration is deliberately idempotent:
-- deployment and the scheduled refresh can both initialize the integration.
CREATE TABLE IF NOT EXISTS sanctions_datasets (
  snapshot_id TEXT PRIMARY KEY,
  content_hash TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('loading', 'ready')),
  provider TEXT NOT NULL,
  checked_at TEXT NOT NULL,
  activated_at TEXT,
  source_metadata_json TEXT NOT NULL,
  entity_count INTEGER NOT NULL CHECK (entity_count > 0),
  name_count INTEGER NOT NULL CHECK (name_count >= entity_count)
);

CREATE TABLE IF NOT EXISTS sanctions_names (
  snapshot_id TEXT NOT NULL REFERENCES sanctions_datasets(snapshot_id),
  name_id TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  list TEXT NOT NULL CHECK (list IN ('sdn', 'non-sdn')),
  primary_name TEXT NOT NULL,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  sorted_name TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  programs TEXT NOT NULL,
  PRIMARY KEY (snapshot_id, name_id)
);
CREATE INDEX IF NOT EXISTS idx_sanctions_names_normalized
  ON sanctions_names(snapshot_id, normalized_name);
CREATE INDEX IF NOT EXISTS idx_sanctions_names_sorted
  ON sanctions_names(snapshot_id, sorted_name);

-- Tokens are encoded character grams generated by the same helper used by
-- screening. This index finds typo candidates without scanning every name.
CREATE VIRTUAL TABLE IF NOT EXISTS sanctions_name_search USING fts5(
  snapshot_id UNINDEXED,
  name_id UNINDEXED,
  search_terms,
  tokenize = 'ascii'
);

CREATE TABLE IF NOT EXISTS sanctions_active (
  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
  snapshot_id TEXT NOT NULL REFERENCES sanctions_datasets(snapshot_id),
  last_success_checked_at TEXT NOT NULL
);
